# Use a base image with JDK 21
FROM eclipse-temurin:21-jdk
# Set the working directory
WORKDIR /app
# Copy the application JAR to the container
COPY target/spring-boot-docker-0.0.1-SNAPSHOT.jar app.jar
# Expose the application port
EXPOSE 8084

# Run the Java application
ENTRYPOINT ["java", "-jar", "app.jar"]